enum EAuthentication {
  IS_LOGGED_IN = 'VPS|AUTHENTICATION|IS_LOGGED_IN',
  USERNAME = 'VPS|AUTHENTICATION|USERNAME',
  ROLE = 'VPS|AUTHENTICATION|ROLE',
  AUTHENTICATION_KEY = 'VPS|AUTHENTICATION|AUTHENTICATION_KEY'
}

export default EAuthentication;
