enum EEducation {
  PRIMARY_SCHOOL = 'PRIMARY_SCHOOL',
  SECONDARY_SCHOOL = 'SECONDARY_SCHOOL',
  HIGH_SCHOOL = 'HIGH_SCHOOL',
  UNIVERSITY = 'UNIVERSITY',
  MASTER_OF_SCIENCE = 'MASTER_OF_SCIENCE',
  DOCTOR_OF_PHILOSOPHY = 'DOCTOR_OF_PHILOSOPHY',
}

export default EEducation;
